---
title: "saldo_10_20"
output: html_document
date: "2022-12-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(statnipokladna)
```

```{r}
cz_codes <- read.csv("../municipality_codes/cz-structure-enriched.csv", colClasses = c("ico"="character"))
m
icos <- cz_codes$ico
```

```{r}
budget <- sp_get_table("budget-local", seq(2010,2020), ico=icos)
budget <- budget %>% mutate(vykaz_date=sprintf("%s-%s-31", vykaz_year, vykaz_month))
```

```{r}
cats <- sp_get_codelist("polozka")
sp_codelists
budget_enriched <-budget %>% sp_add_codelist(cats) %>% sp_add_codelist("polozka")
```

```{r}
budget_specific_columns <- budget_enriched[,c("vykaz_year", "ico", "budget_spending","druh")]
budget_specific_columns <- budget_specific_columns %>% rename("year" = "vykaz_year",
                                                        "budget_spending_CZK" = "budget_spending",
                                                        "type" = "druh")
budget_specific_columns <-na.omit(budget_specific_columns)
budget_specific_columns <- budget_specific_columns %>% group_by(year, ico, type) %>% summarise(budget_spending_CZK=sum(budget_spending_CZK))
library(tidyr)
budget_specific_columns <- spread(budget_specific_columns, type, budget_spending_CZK)
budget_specific_columns$saldo <- budget_specific_columns$Příjmy - budget_specific_columns$Výdaje
```

```{r}
write.csv(budget_specific_columns,"~/Desktop/cr-data/statnipokladna/saldo_2010_2020.csv", row.names=FALSE)

```
